server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: org.apache.commons.dbcp.BasicDataSource
  mail:
    host: smtp.qq.com
    port: 587
    username: 670482466@qq.com
    password: gnbttuubmssqbaid
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 0
logging:
  file: springboot.log
  level:
    com.boot.dao: debug

