server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: org.apache.commons.dbcp.BasicDataSource
  mail:
    host: smtp.qq.com
    port: 587
    username: 670482466@qq.com
    password: gnbttuubmssqbaid
logging:
  file: springboot.log
  level:
    com.boot.dao: debug

